### ISSUE TITLE
Website demo no longer working?

### ISSUE THREAD

**Issue by cst0** [mbforbes/social-chemistry-101#1]
Not a huge deal since you've provided the weights and I should just download and use that anyway, but just a heads-up that yesterday and today the online demo no longer seems to be working: I can type in a scenario (or use one of the provided ones), and clicking "generate" gets caught in a "generating rules-of-thumb" loop forever. The dataset browser is also stuck in a "loading dataset" loop.

**Comment by mbforbes** [comment]
Hey @cst0, thank you for the heads up! You're right, they're both broken.

It looks like the backend—hosted by AI2—has enabled a new CORS policy that's preventing the API from being used by the website:

> blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I'll see if we can fix this, but it might be a few days before I can get to it.

**Comment by mbforbes** [comment]
Thanks again for reporting this @cst0, the wizards at AI2 fixed the backend and the demo is running now. Please let me know if you run into any issues!
