### ISSUE TITLE
What license is the Social Chemistry 101 dataset?

### ISSUE THREAD

**Issue by chanind** [mbforbes/social-chemistry-101#2]
I couldn't find a license in this repo, the paper, or the website for using this dataset

**Comment by mbforbes** [comment]
Hey David, thanks for the question, and apologies we don't have that figured out! Funny how licensing it isn't something we usually consider. We generally expect other researches to use it as desired in their research, but don't anticipate interest beyond that.

I'm checking about this now. I will give you an answer as soon as I have one. (I hope within a day or two, but it's beyond my purview to decide.)

**Comment by mbforbes** [comment]
We'll license it as [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). I'll update the readme soon and close this issue. Thanks again for the question!

**Comment by chanind** [comment]
Thank you so much!
